// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jSrpzcnmBo0qDEnlp8kNyDfUdl69MsI',
    appId: '1:431796567127:android:c735eef2ad7d5b56f3f712',
    messagingSenderId: '431796567127',
    projectId: 'phoneauthentication-c2483',
    storageBucket: 'phoneauthentication-c2483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWkv6U69UICT3nJ2Wuh6ACpDLMDUgWp8',
    appId: '1:431796567127:ios:b10c6613ea6019cbf3f712',
    messagingSenderId: '431796567127',
    projectId: 'phoneauthentication-c2483',
    storageBucket: 'phoneauthentication-c2483.appspot.com',
    androidClientId: '431796567127-pdf9fl0sloo67is1d18guclcr3qr6cbk.apps.googleusercontent.com',
    iosClientId: '431796567127-ou8d8kd9e0j7frvt944vrr68s1cu9r1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentAuthentication',
  );
}
